/**
 ******************************************************************************
 * @file           : main.c (COMPLETE INTEGRATION EXAMPLE)
 * @brief          : Audio Spectrum Analyzer — I2C2 OLED + I2S Microphone
 * @author         : Kushal Pitaliya
 * @date           : 2026-04-08
 ******************************************************************************
 *
 * HARDWARE:
 *   - STM32F411CEU6 (Black Pill) @ 100 MHz
 *   - INMP441 MEMS Microphone (I2S2)
 *   - SSD1306 OLED Display 128x64 (I2C2)
 *
 * WIRING:
 *   INMP441:
 *     VDD → 3.3V,  GND → GND
 *     WS  → PA4  (I2S2_WS)
 *     SCK → PB10 (I2S2_CK)
 *     SD  → PC3  (I2S2_SD)
 *     L/R → GND  (Left channel)
 *
 *   SSD1306 (I2C2):
 *     VCC → 3.3V,  GND → GND
 *     SCL → PB10 (I2C2_SCL)
 *     SDA → PB3  (I2C2_SDA)
 *
 * NOTE: PB10 is shared between I2S2_CK and I2C2_SCL in the pin table.
 *       Verify your CubeMX pin assignments — you may need to remap
 *       I2S2 clock to a different pin if there's a conflict.
 *
 * SETUP:
 *   1. Copy MIC/, OLED/, FFT/, SPECTRUM/, DISPLAY/ into Core/ of your project
 *   2. Add include paths for each folder
 *   3. Enable CMSIS-DSP, define ARM_MATH_CM4, __FPU_PRESENT=1
 *   4. Configure I2S2 + DMA and I2C2 in CubeMX
 *   5. Paste this code into your main.c (or adapt the while-loop)
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <string.h>

/* User module includes */
#include "i2s_mic.h"
#include "ssd1306.h"
#include "fft_processor.h"
#include "spectrum.h"
#include "spectrum_display.h"

/* Private variables ---------------------------------------------------------*/
I2C_HandleTypeDef hi2c2;       /* I2C2 for OLED display */
I2S_HandleTypeDef hi2s2;       /* I2S2 for microphone */
DMA_HandleTypeDef hdma_spi2_rx;

/* Private function prototypes (generated by CubeMX) -------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_I2C2_Init(void);
static void MX_I2S2_Init(void);

/* ============================================================================
 * MAIN FUNCTION
 * ============================================================================ */
int main(void)
{
    /* HAL Init */
    HAL_Init();
    SystemClock_Config();
    
    /* Initialize peripherals (GPIO, DMA, I2C, I2S) */
    MX_GPIO_Init();
    MX_DMA_Init();      /* Must be before I2S init */
    MX_I2C2_Init();     /* I2C2 for OLED */
    MX_I2S2_Init();     /* I2S2 for microphone */

    /* -----------------------------------------------------------------------
     * Initialize All Modules
     * ----------------------------------------------------------------------- */
    
    /* 1. Initialize OLED Display (I2C2) */
    ssd1306_Init();
    DISPLAY_Init();
    
    /* 2. Show startup title for 2 seconds */
    DISPLAY_ShowTitle();
    HAL_Delay(2000);
    
    /* 3. Initialize FFT processor (pre-computes Hanning window) */
    FFT_Init();
    
    /* 4. Initialize spectrum analyzer */
    SPECTRUM_Init();
    
    /* 5. Initialize and start I2S microphone DMA */
    MIC_Init(&hi2s2);
    MIC_Start();
    
    /* -----------------------------------------------------------------------
     * Main Loop — Audio Processing Pipeline
     *
     * Data flow:
     *   INMP441 → DMA → mic_audio_buf[512]
     *                  → FFT_Process → fft_magnitude[256]
     *                  → SPECTRUM_Update → bar_heights[8]
     *                  → DISPLAY_DrawBarsWithPeaks → SSD1306 OLED
     * ----------------------------------------------------------------------- */
    while (1)
    {
        /* Check if new audio data is ready from DMA */
        if (mic_data_ready)
        {
            /* Clear the flag FIRST to avoid missing the next interrupt */
            mic_data_ready = 0;
            
            /* STEP 1: Run 512-point FFT on the audio buffer */
            FFT_Process(mic_audio_buf);
            
            /* STEP 2: Map 256 FFT bins → 8 frequency bars */
            SPECTRUM_Update(fft_magnitude);
            
            /* STEP 3: Render bars + peak-hold on OLED */
            DISPLAY_DrawBarsWithPeaks(
                SPECTRUM_GetBarHeights(), 
                SPECTRUM_GetPeaks()
            );
        }
    }
}

/* ============================================================================
 * HAL I2S DMA CALLBACKS
 * Wire these to the MIC module's processing routines.
 * ============================================================================ */

/**
 * @brief I2S DMA Half Transfer Complete — first half of DMA buffer filled
 */
void HAL_I2S_RxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2) {  /* I2S2 uses SPI2 peripheral */
        MIC_HalfTransferCallback();
    }
}

/**
 * @brief I2S DMA Full Transfer Complete — second half of DMA buffer filled
 */
void HAL_I2S_RxCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2) {
        MIC_FullTransferCallback();
    }
}
