/**
 ******************************************************************************
 * @file           : main.c (COMPLETE INTEGRATION EXAMPLE)
 * @brief          : Audio Spectrum Analyzer — I2C2 OLED + I2S Microphone
 * @author         : Kushal Pitaliya
 * @date           : 2026-04-08
 ******************************************************************************
 *
 * HARDWARE:
 *   - STM32F411CEU6 (Black Pill) @ 100 MHz
 *   - INMP441 MEMS Microphone (I2S2)
 *   - SSD1306 OLED Display 128x64 (I2C2)
 *
 * WIRING:
 *   INMP441:
 *     VDD → 3.3V,  GND → GND
 *     WS  → PA4  (I2S2_WS)
 *     SCK → PB10 (I2S2_CK)
 *     SD  → PC3  (I2S2_SD)
 *     L/R → GND  (Left channel)
 *
 *   SSD1306 (I2C2):
 *     VCC → 3.3V,  GND → GND
 *     SCL → PB10 (I2C2_SCL)
 *     SDA → PB3  (I2C2_SDA)
 *
 * NOTE: PB10 is shared between I2S2_CK and I2C2_SCL in the pin table.
 *       Verify your CubeMX pin assignments — you may need to remap
 *       I2S2 clock to a different pin if there's a conflict.
 *
 * SETUP:
 *   1. Copy MIC/, OLED/, FFT/, SPECTRUM/, DISPLAY/ into Core/ of your project
 *   2. Add include paths for each folder
 *   3. Enable CMSIS-DSP, define ARM_MATH_CM4, __FPU_PRESENT=1
 *   4. Configure I2S2 + DMA and I2C2 in CubeMX
 *   5. Paste this code into your main.c (or adapt the while-loop)
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <string.h>

/* User module includes */
#include "i2s_mic.h"
#include "ssd1306.h"
#include "fft_processor.h"
#include "spectrum.h"
#include "spectrum_display.h"

/* Private variables ---------------------------------------------------------*/
I2C_HandleTypeDef hi2c2;       /* I2C2 for OLED display */
I2S_HandleTypeDef hi2s2;       /* I2S2 for microphone */
DMA_HandleTypeDef hdma_spi2_rx;

/* Private function prototypes (generated by CubeMX) -------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_I2C2_Init(void);
static void MX_I2S2_Init(void);

/* ============================================================================
 * MAIN FUNCTION
 * ============================================================================ */
int main(void)
{
    /* HAL Init */
    HAL_Init();
    SystemClock_Config();
    
    /* Initialize peripherals (GPIO, DMA, I2C, I2S) */
    MX_GPIO_Init();
    MX_DMA_Init();      /* Must be before I2S init */
    MX_I2C2_Init();     /* I2C2 for OLED */
    MX_I2S2_Init();     /* I2S2 for microphone */

    /* -----------------------------------------------------------------------
     * Initialize All Modules
     * ----------------------------------------------------------------------- */
    
    /* 1. Initialize OLED Display (I2C2) */
    ssd1306_Init();
    DISPLAY_Init();
    
    /* 2. Show startup title for 2 seconds */
    DISPLAY_ShowTitle();
    HAL_Delay(2000);
    
    /* 3. Initialize FFT processor (pre-computes Hanning window) */
    FFT_Init();
    
    /* 4. Initialize spectrum analyzer */
    SPECTRUM_Init();
    
    /* 5. Initialize and start I2S microphone DMA */
    MIC_Init(&hi2s2);
    MIC_Start();
    
    /* -----------------------------------------------------------------------
     * Main Loop — Audio Processing Pipeline
     *
     * Data flow:
     *   INMP441 → DMA → mic_audio_buf[512]
     *                  → FFT_Process → fft_magnitude[256]
     *                  → SPECTRUM_Update → bar_heights[8]
     *                  → DISPLAY_DrawBarsWithPeaks → SSD1306 OLED
     * ----------------------------------------------------------------------- */
    while (1)
    {
        /* Check if new audio data is ready from DMA */
        if (mic_data_ready)
        {
            /* Clear the flag FIRST to avoid missing the next interrupt */
            mic_data_ready = 0;
            
            /* STEP 1: Run 512-point FFT on the audio buffer */
            FFT_Process(mic_audio_buf);
            
            /* STEP 2: Map 256 FFT bins → 8 frequency bars */
            SPECTRUM_Update(fft_magnitude);
            
            /* STEP 3: Render bars + peak-hold on OLED */
            DISPLAY_DrawBarsWithPeaks(
                SPECTRUM_GetBarHeights(), 
                SPECTRUM_GetPeaks()
            );
        }
    }
}

/* ============================================================================
 * HAL I2S DMA CALLBACKS
 * Wire these to the MIC module's processing routines.
 * ============================================================================ */

/**
 * @brief I2S DMA Half Transfer Complete — first half of DMA buffer filled
 */
void HAL_I2S_RxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2) {  /* I2S2 uses SPI2 peripheral */
        MIC_HalfTransferCallback();
    }
}

/**
 * @brief I2S DMA Full Transfer Complete — second half of DMA buffer filled
 */
void HAL_I2S_RxCpltCallback(I2S_HandleTypeDef *hi2s)
{
    if (hi2s->Instance == SPI2) {
        MIC_FullTransferCallback();
    }
}

/* ============================================================================
 * PERIPHERAL INITIALIZATION
 * These are generated by CubeMX — shown here for reference / self-contained use.
 * If CubeMX generated your own versions, use those instead.
 * ============================================================================ */

/**
 * @brief System Clock Configuration — 100 MHz from 25 MHz HSE
 */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
    RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState       = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM       = 25;            /* 25 MHz / 25 = 1 MHz  */
    RCC_OscInitStruct.PLL.PLLN       = 200;           /* × 200 = 200 MHz      */
    RCC_OscInitStruct.PLL.PLLP       = RCC_PLLP_DIV2; /* / 2 = 100 MHz SYSCLK */
    RCC_OscInitStruct.PLL.PLLQ       = 4;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) Error_Handler();

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;  /* 50 MHz  */
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;  /* 100 MHz */
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK) Error_Handler();

    /* I2S PLL — must yield ~44.1 kHz audio clock */
    PeriphClkInitStruct.PeriphClockSelection  = RCC_PERIPHCLK_I2S;
    PeriphClkInitStruct.PLLI2S.PLLI2SN        = 86;
    PeriphClkInitStruct.PLLI2S.PLLI2SR        = 2;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInitStruct) != HAL_OK) Error_Handler();
}

/**
 * @brief GPIO Initialization — enable port clocks
 */
static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOH_CLK_ENABLE();
}

/**
 * @brief DMA Initialization — I2S2 uses DMA1 Stream3
 */
static void MX_DMA_Init(void)
{
    __HAL_RCC_DMA1_CLK_ENABLE();
    HAL_NVIC_SetPriority(DMA1_Stream3_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(DMA1_Stream3_IRQn);
}

/**
 * @brief I2C2 Initialization — 400 kHz fast mode for SSD1306
 */
static void MX_I2C2_Init(void)
{
    hi2c2.Instance             = I2C2;
    hi2c2.Init.ClockSpeed      = 400000;
    hi2c2.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c2.Init.OwnAddress1     = 0;
    hi2c2.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c2.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c2.Init.OwnAddress2     = 0;
    hi2c2.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c2.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c2) != HAL_OK) Error_Handler();
}

/**
 * @brief I2S2 Initialization — 24-bit Philips I2S @ 44.1 kHz, Master RX
 */
static void MX_I2S2_Init(void)
{
    hi2s2.Instance         = SPI2;
    hi2s2.Init.Mode        = I2S_MODE_MASTER_RX;
    hi2s2.Init.Standard    = I2S_STANDARD_PHILIPS;
    hi2s2.Init.DataFormat  = I2S_DATAFORMAT_24B;
    hi2s2.Init.MCLKOutput  = I2S_MCLKOUTPUT_DISABLE;
    hi2s2.Init.AudioFreq   = I2S_AUDIOFREQ_44K;
    hi2s2.Init.CPOL        = I2S_CPOL_LOW;
    hi2s2.Init.ClockSource = I2S_CLOCK_PLL;
    if (HAL_I2S_Init(&hi2s2) != HAL_OK) Error_Handler();
}

/**
 * @brief Error Handler — halt on peripheral init failure
 */
void Error_Handler(void)
{
    __disable_irq();
    while (1) { /* Stay here — use debugger to find the cause */ }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line) { }
#endif

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/

